In [2]:
# In this notebook, we are going to cover some of the most fundamentals concepts of tensors using TensorFlow

# In this notebook, we are going to cover some of the most fundamentals concepts of tensors using TensorFlow

More specifically, we are going to cover:
*introdcution to tensors
*Getting information from tensors
*Manipulating tensors
*Tensors & Numpy
*Using @tf.function (a way to speed up your regular python functions)
*Using GPUs with Tensorflow(or TPUS)
*Exercises to tryu fro yourself!


Introduction to Tensors


In [2]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [4]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [6]:
#Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#Check the dimension of our vector
vector.ndim

1

In [8]:
#Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
#Create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype = tf.float16) #specify the datatype with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
#Lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

In [14]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
#Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
changeable_tensor[0] = 7

TypeError: ignored

In [16]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)

AttributeError: ignored

# Create random tensors

In [17]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

# Shuffle the order of elements in a tensor

In [18]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

2

In [19]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# Other ways to make Tensors

In [20]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Turn Numpy arrays into tensors

In [22]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A

#x = tf.constant(some_matrix)
#y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
A = tf.constant(numpy_A, shape =(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting informations from tensors

Shape
Rank
Axis or dimension
Size

In [24]:
#Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [26]:
#Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor 120


# Indexing tensors

Tensors can be indexed just like Python lists

In [27]:
#Get the first 2 elements of each dimensions
rank_4_tensor = tf.zeros(shape= [2, 3, 4, 5])
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
#Get the first element from each dimension except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
#Create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.shape

TensorShape([2, 2])

In [30]:
#Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [31]:
#Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [32]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis= -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
tf.expand_dims(rank_2_tensor, axis= 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

# Manipulating tensors (tensor operations)



In [34]:
"You can add values to a tensor using the addition operator"
tensor = tf.constant([[10,7],[3,4]])
tensor +  10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [35]:
tensor *  10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [37]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [38]:
#Matrix multiplication
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [39]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [40]:
tensor.shape

TensorShape([2, 2])

In [41]:
x = tf.constant([[1,2],
            [3,4],
            [5,6]])

Y  = tf.constant([[7,8],
                  [9,10],
                  [11,12]])
x,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [42]:
tf.matmul(x, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [43]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

# The dot product

Matrix multiplication is also referred to as the dot product.

In [44]:
x, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [45]:
#Perform the dot product on X and Y (requires to be transposed)
tf.tensordot(tf.transpose(x), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [46]:
tf.matmul(x, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [47]:
tf.matmul(x, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

# Changing the datatype of a tensor

In [49]:
#Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [50]:
#Create a new tensor with default datatype (float32)
C = tf.constant([1, 7])
C.dtype

tf.int32

In [52]:
#Change from 32 to 16
B = tf.cast(B, dtype = tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

# Aggregating Tensors

In [53]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [54]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [56]:
#Creating a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([77, 11, 28, 36, 81, 94, 26, 26, 75,  0, 38, 12, 93, 44, 25, 84, 96,
       52,  1, 90, 45, 78, 92, 43, 19, 99, 16,  3, 14, 44, 85, 41,  5, 62,
       52, 64, 15, 81, 77, 52, 92, 31, 40,  4, 26, 31, 92, 92, 50, 87])>

In [57]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [58]:
#Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [59]:
#Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [60]:
#Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [61]:
#Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2521>

In [65]:
#Find the standar deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.279444>

In [66]:
#Find the variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=978.40356>

# Positional Maximum and Minimum


In [68]:
#Create a new tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [69]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [70]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [71]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [72]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Squeezing a tensor (removing all single dimensions)

In [74]:
### Squeezing a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape =[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [76]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [79]:
G_squeezed= tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# One-hot encoding tensors

In [87]:
### One hot-encoding
some_list = [0, 1, 2, 3] #could be red, green, blue, purple

#One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [85]:
#Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo i love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo i love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo i love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo i love deep learning']],
      dtype=object)>

# Squaring, log, square root

In [88]:
#Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [89]:
#Square it
H = tf.square(H)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [91]:
#Squareroot
H = tf.sqrt(tf.cast(H, dtype=tf.float32))
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [93]:
H = tf.math.log(tf.cast(H, dtype=tf.float32))
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and Numpy

In [94]:
#Create a tensor direclty from a Numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [95]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [97]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [98]:
#The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Finding access to GPUS

In [3]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
!nvidia-smi

Tue Nov 28 15:56:05 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8    11W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🛠 00. TensorFlow Fundamentals Exercises

In [7]:
#Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()
vector = tf.constant([2,4])
scalar = tf.constant(1)
matrix = tf.constant([[2,4,4],[5,8,9]])

In [9]:
#Find the shape, rank and size of the tensors you created in 1.
vector.shape, vector.ndim, tf.size(vector)


(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [10]:
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([1]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [11]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 3]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [14]:
#Create two tensors containing random values between 0 and 1 with shape [5, 300]
import numpy as np
tensor_1 = tf.constant(np.random.random(), shape = [5,300])
tensor_2 = tf.constant(np.random.random(), shape = [5,300])

In [17]:
tf.matmul(tensor_1, tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[239.54071, 239.54071, 239.54071, 239.54071, 239.54071],
       [239.54071, 239.54071, 239.54071, 239.54071, 239.54071],
       [239.54071, 239.54071, 239.54071, 239.54071, 239.54071],
       [239.54071, 239.54071, 239.54071, 239.54071, 239.54071],
       [239.54071, 239.54071, 239.54071, 239.54071, 239.54071]],
      dtype=float32)>

In [18]:
tensor_1 * tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.7984688, 0.7984688, 0.7984688, ..., 0.7984688, 0.7984688,
        0.7984688],
       [0.7984688, 0.7984688, 0.7984688, ..., 0.7984688, 0.7984688,
        0.7984688],
       [0.7984688, 0.7984688, 0.7984688, ..., 0.7984688, 0.7984688,
        0.7984688],
       [0.7984688, 0.7984688, 0.7984688, ..., 0.7984688, 0.7984688,
        0.7984688],
       [0.7984688, 0.7984688, 0.7984688, ..., 0.7984688, 0.7984688,
        0.7984688]], dtype=float32)>

In [19]:
tf.tensordot(tensor_1, tf.transpose(tensor_2), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[239.54071, 239.54071, 239.54071, 239.54071, 239.54071],
       [239.54071, 239.54071, 239.54071, 239.54071, 239.54071],
       [239.54071, 239.54071, 239.54071, 239.54071, 239.54071],
       [239.54071, 239.54071, 239.54071, 239.54071, 239.54071],
       [239.54071, 239.54071, 239.54071, 239.54071, 239.54071]],
      dtype=float32)>

In [20]:
#Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
tensor_2 = tf.constant(np.random.random(), shape = [224,224,3])

In [23]:
tf.reduce_max(tensor_2, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.80515

In [24]:
tf.reduce_min(tensor_2, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.8051566, 0.8051566],
       [0.8051566, 0.80515

In [25]:
#Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
tensor_random = tf.constant(np.random.randint(1,300), shape = [1,224,224,3])

In [26]:
tensor_random

<tf.Tensor: shape=(1, 224, 224, 3), dtype=int32, numpy=
array([[[[222, 222, 222],
         [222, 222, 222],
         [222, 222, 222],
         ...,
         [222, 222, 222],
         [222, 222, 222],
         [222, 222, 222]],

        [[222, 222, 222],
         [222, 222, 222],
         [222, 222, 222],
         ...,
         [222, 222, 222],
         [222, 222, 222],
         [222, 222, 222]],

        [[222, 222, 222],
         [222, 222, 222],
         [222, 222, 222],
         ...,
         [222, 222, 222],
         [222, 222, 222],
         [222, 222, 222]],

        ...,

        [[222, 222, 222],
         [222, 222, 222],
         [222, 222, 222],
         ...,
         [222, 222, 222],
         [222, 222, 222],
         [222, 222, 222]],

        [[222, 222, 222],
         [222, 222, 222],
         [222, 222, 222],
         ...,
         [222, 222, 222],
         [222, 222, 222],
         [222, 222, 222]],

        [[222, 222, 222],
         [222, 222, 222],
         [222, 222

In [28]:
new_tensor = tf.squeeze(tensor_random)
new_tensor.shape

TensorShape([224, 224, 3])

In [34]:
new_tensor = tf.constant(np.random.randint(0,20, 10), shape = 10)

In [35]:
new_tensor

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([12,  7,  5,  1,  5,  3,  6,  5, 18,  5])>

In [36]:
tf.argmax(new_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [38]:
one = tf.one_hot(new_tensor, depth = 10)
one

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>